name: Cypress Tests E2E 

on: [push]

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Cypress.io
        uses: cypress-io/github-action@v4.1.1
      - run: npm run build
      - run: npm run dev &
      - run: npm test-e2e
